App/Vroom/Vroom/Controllers/BikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vroom.Models;
using Vroom.Models.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting.Internal;

namespace Vroom.Controllers
{
    public class BikeController : Controller
    {
        private readonly VroomDbContext _VDbContext;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public BikeViewModel BikeVM { get; set; }

        public BikeController(VroomDbContext VDbContext, HostingEnvironment hostingEnvironment)
        {
            _VDbContext = VDbContext;
            _hostingEnvironment = hostingEnvironment;

            BikeVM = new BikeViewModel()
            {
                Makes = _VDbContext.Makes.ToList(),
                Models = _VDbContext.Models.ToList(),
                Bike = new Models.Bike()
            };
        }
        public IActionResult Index()
        {
            var Bikes = _VDbContext.Bikes.Include(m => m.Make).Include(m => m.Model);
            return View(Bikes.ToList());
        }


        //HTTP GET
        public IActionResult Create()
        {
            return View(BikeVM);
        }


        //Post Method
        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost()
        {
            if (!ModelState.IsValid)
            {
                BikeVM.Makes = _VDbContext.Makes.ToList();
                BikeVM.Models = _VDbContext.Models.ToList();
                return View(BikeVM);
            }
            _VDbContext.Bikes.Add(BikeVM.Bike);
            _VDbContext.SaveChanges();

            /////////////////////////
            /// Save Bike Logic//////
            ////////////////////////

            //Get bike Id we have saved in db
            var BikeId = BikeVM.Bike.Id;

            //Get wwwrootPath to save the file on server 
            string wwwrootPath = _hostingEnvironment.WebRootPath;

            //Get the uploaded files 
            var files = HttpContext.Request.Form.Files;

            //Get the reference of DbSet for the bike we just saved in database 
            var SavedBike = _VDbContext.Bikes.Find(BikeId);

            //Upload the files on server and save the image path uploaded by user if any 

            if (files.Count != 0)
            {
                var ImagePath = @"images\bike\";
                var Extension = Path.GetExtension(files[0].FileName);
                var RelativeImagePath = ImagePath + BikeId + Extension;
                var AbsImagePath = Path.Combine(wwwrootPath, RelativeImagePath);

                //Upload file on server
                using (var fileStream = new FileStream(AbsImagePath, FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }

                //Set the image path on database 
                SavedBike.ImagePath = RelativeImagePath;
                _VDbContext.SaveChanges();
            }
            /////////////////////////

            



            return RedirectToAction(nameof(Index));
        }

        //Http Get
        //public IActionResult Edit(int id)
        //{
        //    ModelVM.Model = _VDbContext.Models.Include(m => m.make).SingleOrDefault(m => m.Id == id);
        //    if (ModelVM.Model == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(ModelVM);
        //}

        //[HttpPost, ActionName("Edit")]
        //public IActionResult EditPost()
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(ModelVM);
        //    }
        //    _VDbContext.Update(ModelVM.Model);
        //    _VDbContext.SaveChanges();
        //    return RedirectToAction(nameof(Index));
        //}

        public IActionResult Delete(int id)
        {
            var bike = _VDbContext.Bikes.Find(id);
            if (bike == null)
            {
                return NotFound();
            }
            _VDbContext.Bikes.Remove(bike);
            _VDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

App/Vroom/Vroom/Controllers/MakeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Vroom.Models;

namespace Vroom.Controllers
{
    [Authorize(Roles =("Admin,Executive"))]
    public class MakeController : Controller
    {
        private readonly VroomDbContext _VDbContext;

        public MakeController(VroomDbContext VDbContext)
        {
            _VDbContext = VDbContext;
        }

        public IActionResult Index()
        {
            return View(_VDbContext.Makes.ToList());
        }


        //Http Get Method
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Make make)
        {
            if (ModelState.IsValid)
            {
                _VDbContext.Add(make);
                _VDbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(make);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var make = _VDbContext.Makes.Find(id);
            if(make == null)
            {
                return NotFound();
            }
            _VDbContext.Makes.Remove(make);
            _VDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(Make make)
        {
            if (ModelState.IsValid)
            {
                _VDbContext.Update(make);
                _VDbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(make);
        }
    }
}

App/Vroom/Vroom/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vroom.Models;
using Vroom.Models.ViewModels;

namespace Vroom.Controllers
{
    [Authorize(Roles = ("Admin,Executive"))]
    public class ModelController : Controller
    {
        private readonly VroomDbContext _VDbContext;

        [BindProperty]
        public ModelViewModel ModelVM { get; set; }

        public ModelController(VroomDbContext VDbContext)
        {
            _VDbContext = VDbContext;

            ModelVM = new ModelViewModel()
            {
                Makes = _VDbContext.Makes.ToList(),
                Model = new Models.Model()
            }; 
        }
        public IActionResult Index()
        {
            var model = _VDbContext.Models.Include(m => m.make);
            return View(model);
        }


        //HTTP GET
        public IActionResult Create()
        {
            return View(ModelVM);
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost()
        {
            if (!ModelState.IsValid)
            {
                return View(ModelVM);
            }
            _VDbContext.Models.Add(ModelVM.Model);
            _VDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }   

        //Http Get
        public IActionResult Edit(int id)
        {
            ModelVM.Model = _VDbContext.Models.Include(m => m.make).SingleOrDefault(m => m.Id == id);
            if(ModelVM.Model == null)
            {
                return NotFound();
            }
            return View(ModelVM);
        }

        [HttpPost, ActionName("Edit")]
        public IActionResult EditPost()
        {
            if (!ModelState.IsValid)
            {
                return View(ModelVM);
            }
            _VDbContext.Update(ModelVM.Model);
            _VDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var model = _VDbContext.Models.Find(id);
            if (model == null)
            {
                return NotFound();
            }
            _VDbContext.Models.Remove(model);
            _VDbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

App/Vroom/Vroom/Views/Shared/_Layout.cshtml
@using Vroom.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vroom</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://kit.fontawesome.com/1b5f0f20cd.js" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Vroom</a>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Executive))
                    {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Masters
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Make" asp-action="Index">Makes</a></li>
                            <li><a class="dropdown-item" asp-controller="Model" asp-action="Index">Models</a></li>
                            <li><a class="dropdown-item" asp-controller="Bike" asp-action="Index">Bikes</a></li>
                            @if (User.IsInRole(Roles.Admin))
                            {
                                <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Add User</a></li>
                            }
                        </ul>
                    </li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Vroom</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

App/Vroom/Vroom/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td class="text-right">
    <div class="btn-group" role="group">
        <form method="post" action="Edit">
            <button type="submit" class="btn btn-primary text-right" asp-action="Edit" asp-route-id="@Model"><i class="fas fa-edit"></i></button>
        </form>
        <form method="post" action="Delete">
            <button onclick="if (!confirm('Are you sure you want to delete this item ?')){return false}" type="submit" class="btn btn-danger" asp-action="Delete" asp-route-id="@Model"><i class="fas fa-trash-alt"></i></button>
        </form>
    </div>
</td>